# syntax=docker/dockerfile:1

ARG GO_BUILDER_IMAGE=golang:1.26

FROM --platform=$BUILDPLATFORM ${GO_BUILDER_IMAGE} AS builder

ARG APP_PACKAGE=./cmd/promshim
ARG APP_VERSION=dev
ARG APP_COMMIT=unknown
ARG APP_DATE=unknown

WORKDIR /src
ENV CGO_ENABLED=0

ARG TARGETOS
ARG TARGETARCH
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

COPY go.mod go.sum ./
RUN go mod download
COPY . ./

RUN mkdir -p /out && \
  if [ -z "${APP_PACKAGE}" ]; then \
    echo "APP_PACKAGE is required"; \
    exit 1; \
  fi && \
  go build -trimpath -ldflags="-s -w -X main.version=${APP_VERSION} -X main.commit=${APP_COMMIT} -X main.date=${APP_DATE}" -o /out/service ${APP_PACKAGE}

FROM gcr.io/distroless/static-debian12:nonroot AS runtime

ARG APP_PORT=9090

COPY --from=builder /out/service /usr/local/bin/service
EXPOSE ${APP_PORT}

USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/service"]
