apiVersion: 1

deleteDatasources:
  - name: ClickHouse
    orgId: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    orgId: 1
    type: grafana-clickhouse-datasource
    access: proxy
    url: clickhouse:9000
    user: otel
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      database: observability
      username: otel
      tlsSkipVerify: false
    secureJsonData:
      username: "otel"
      password: "otel"
